### ISSUE TITLE
Background worker raises InvalidSequenceTokenException

### ISSUE THREAD

**Issue by monty241** [aws/aws-logging-dotnet#124]
After starting the monitor, a range of errors is detected by a first chance exception handler. However, the logging happens correctly. It seems the errors are ignored in general.

Sample attached.

**Comment by monty241** [comment]
[sample.txt](https://github.com/aws/aws-logging-dotnet/files/4505729/sample.txt)

**Comment by monty241** [comment]
In the same version AWS.Logger.Core 1.6.0, we also get often a NullReferenceException.

Call stack:

```
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: !! First chance exception handling of type 'NullReferenceException':
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: Object reference not set to an instance of an object.
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: !! All stack traces:
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: !!    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at Invantive.Data.ErrorToTrace.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e) in C:\Users\gle3.WS212\Documents\ws-master\Invantive.SQL\src\Invantive.Data.Interfaces\Utilities\ErrorToTrace.cs:line 203
   at AWS.Logger.Core.AWSLoggerCore.<>c.<SendMessages>b__32_0(InputLogEvent ev1, InputLogEvent ev2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at AWS.Logger.Core.AWSLoggerCore.<SendMessages>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AWS.Logger.Core.AWSLoggerCore.SendMessages(CancellationToken token)
   at AWS.Logger.Core.AWSLoggerCore.<Monitor>d__31.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.Task.DelayPromise.Complete()
   at System.Threading.Tasks.Task.<>c.<Delay>b__274_1(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: !! All data:
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-df335f29-50d7-4e96-91d3-e4dc7e4fec59-9: !! property-0-System.NullReferenceException-HResult='-2147467261'
property-0-System.NullReferenceException-Source='AWS.Logger.Core'
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-f763676d-7db3-4e72-ae39-b1be962fc677-9: !! First chance exception handling of type 'InvalidOperationException':
19:14:58.13938-EVT-CurrentDomain_FirstChanceException-f763676d-7db3-4e72-ae39-b1be962fc677-9: Failed to compare two elements in the array.

```

**Comment by monty241** [comment]
Or:

```
1 validation error detected: Value null at 'logEvents' failed to satisfy constraint: Member must not be null
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
```

HTTP status BadRequest

Inner exception:
```
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
```

**Comment by monty241** [comment]
NullReferenceException is raised on:
```
 _repo._request.LogEvents.Sort((ev1, ev2) => ev1.Timestamp.CompareTo(ev2.Timestamp));
```
with ev1 being null, caused by the slot at index 4 of _repo._request.LogEvents being null instead of an InputLogEvent.

**Comment by monty241** [comment]
Also, a WebException can be triggered due to a race condition:

AddMessage does an add on _request.LogEvents.Add in line 615, whereas the monitor thread can be executing:
```
_repo._request.LogEvents.Sort((ev1, ev2) => ev1.Timestamp.CompareTo(ev2.Timestamp));
                var response = await _client.PutLogEventsAsync(_repo._request, token).ConfigureAwait(false)
```
But the requests are a List...

**Comment by monty241** [comment]
It is unclear to me what the original design was but the SendMessages could lock the request, put the request in a separate object and create a new object for the AddMessage to fill up again.

**Comment by monty241** [comment]
Studyiong the algorithm solutions seems to be to switch from:
```
awsLoggerCore = new AWSLoggerCore(awsLoggerConfig, logGroup);
awsLoggerCore.StartMonitor();
```
to
```
awsLoggerCore = new AWSLoggerCore(awsLoggerConfig, logGroup);
```
The source code reveals that the constructor already starts the monitor. The StartMonitor does not check whether it is already running.

Suggestion:
* Make explicit in documentation on constructor that it starts the monitor.
* Add check to StartMonitor whether already running / singleton.
* Or (less desired, multiple uploaders are hard given the time-based order) implement correct locking to allow multiple monitors to be running.
