### ISSUE TITLE
IOException when AWS.Logger.Core on logging exceptions.

### ISSUE THREAD

**Issue by monty241** [aws/aws-logging-dotnet#125]
When an exception occurs internally in AWS.Logger.Core 1.6.0, an effort is made to log them to a file. However, it seems that the access from multiple parallel executing activities is not sufficiently coordinated, leading to numerous errors in the form:
```
Exception caught when writing error log to fileSystem.IO.IOException: The process cannot access the file '...\bin\net472\aws-logger-errors.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at AWS.Logger.Core.AWSLoggerCore.LogLibraryError(Exception ex, String LibraryLogFileName)
Exception caught when writing error log to fileSystem.IO.IOException: The process cannot access the file 'C:\Users\gle3.WS212\Documents\ws-master\Invantive.Producer\solutions\99-Invantive.Producer\bin\net472\aws-logger-errors.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at AWS.Logger.Core.AWSLoggerCore.LogLibraryError(Exception ex, String LibraryLogFileName)
```

Suggestion is to improve logging of errors. Only some of them make it into the file.

**Comment by monty241** [comment]
Duplicate of #124.
StartMonitor is auto-started from constructor and StartMonitor does not check for monitor already running.
