### ISSUE TITLE
Error AWSTarget Target[(unnamed)]: Error initializing target Exception:

### ISSUE THREAD

**Issue by abdulkhn8** [aws/aws-logging-dotnet#48]
Error AWSTarget Target[(unnamed)]: Error initializing target Exception: System.TypeLoadException: 
Could not resolve type with token 01000043 
(from typeref, class/assembly Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604)
  at AWS.Logger.Core.AWSLoggerCore..ctor (AWS.Logger.AWSLoggerConfig config, System.String logType) [0x0002a] in D:\Jenkins\jobs\aws-logging-dotnet\workspace\src\AWS.Logger.Core\Core\AWSLoggerCore.cs:43 
  at NLog.AWS.Logger.AWSTarget.InitializeTarget () [0x00092] in D:\Jenkins\jobs\aws-logging-dotnet\workspace\src\NLog.AWS.Logger\AWSTarget.cs:178 
  at NLog.Targets.Target.Initialize (NLog.Config.LoggingConfiguration configuration) [0x00026] in <bba6d1a0b0524939951726a5aab2f401>:0

**Comment by thanhcs** [comment]
I got the same issue. Please help.

**Comment by thanhcs** [comment]
Thanks for sharing your solution, @abdulkhn8.

In my case, I only have CognitoAWSCredentials (which is created by identity pool id) because this is an mobile app, we don't want to store specific keypair in the app. That is why I tried to set `Credentials = awsCredentials `in awsTarget.

Besides, is it because of the lacking support that you abandon this and use not-aws nuget package?

Is there anyone from aws support this?

Thanks,

**Comment by thanhcs** [comment]
the function in DetermineCredentials [AWSLoggerCore.cs](https://github.com/aws/aws-logging-dotnet/blob/master/src/AWS.Logger.Core/Core/AWSLoggerCore.cs) looks at the Credentials prop first which I set it when initializing the target. Why it has an error in CredentialProfileStoreChain. Seems like a reference error.

**Comment by abdulkhn8** [comment]
Actually issue is with AWSCredential class, i have used it in Xamarin ios, there AWSCredential is an abstract class, so cant be instantiated, then i used BasicAWSCredential, which also did not work for me, so after searching i got another package which works fine.
Yes i have to do it in hurry, i waited for them but no response, so i changed this package.

**Comment by normj** [comment]
@abdulkhn8 Sorry you didn't get a response in a timely fashion. The error message implies an older version of AWSSDK.Core was picked up. I understand you have moved on to a different library but I'm curious for future users what if I can make it better. What platform were you running this on? Was this in Xamarin?

**Comment by timc-enthrall** [comment]
We're seeing this same TypeLoadException when using the AWS Target from Xamarin Android / iOS.  The exact same code runs fine on the desktop.  Updating to the newest AWSSDK didn't fix it.

Our usage is vanilla, followed this doco: https://github.com/aws/aws-logging-dotnet/blob/master/README.md.

**Comment by timc-enthrall** [comment]
So it seems like this TypeLoadException isn't an uncommon Xamarin problem: https://stackoverflow.com/questions/41163887/could-not-resolve-type-with-token-0100000f/42511504#42511504.  

What is uncommon is that even from a completely clean (git clean -xdf), completely updated AWSSDK.Core across all of my projects, the problem still persists.  

Changing the Xamarin.Android link mode to 'Full' instantly resulted in a link-time error in the same location (note: we don't usually use Full link mode, was troubleshooting this problem).  Here is that link error:

Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Amazon.Runtime.AWSCredentials AWS.Logger.Core.AWSLoggerCore::DetermineCredentials(AWS.Logger.AWSLoggerConfig)' in assembly: 'AWS.Logger.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain::.ctor(System.String)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by justcoding121** [comment]
I got the same error on Xamarin android with the latest version of AWSSDK.Core (3.3.103) and AWS.Logger.NLog (1.3.2).

System.TypeLoadException: Could not resolve type with token 01000055 from typeref (expected class 'Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain' in assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604')

The error happens as soon as LogManager.Configuration is set crashing the android app. Works fine on console application though.
```

                var accessKey = "my-access-key";
                var secretKey = "my-secret-key";

                var config = new LoggingConfiguration();
                var awsTarget = new AWSTarget()
                {
                    LogGroup = "MyLogGroup",
                    Region = "us-east-2",
                    Credentials = new BasicAWSCredentials(accessKey, secretKey)
                };
                config.AddTarget("aws", awsTarget);
                config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, awsTarget));

                LogManager.Configuration = config;
```
