### ISSUE TITLE
Exception when using AWS.Logger.NLog

### ISSUE THREAD

**Issue by Jhordan92** [aws/aws-logging-dotnet#88]
Now, I must clarify that this exception does not interrupt the process, I noticed it because I have a listener for exceptions before they are catch
AppDomain.CurrentDomain.FirstChanceException += (sender, eventArgs) =>
                {
                    logger.Error(eventArgs.Exception, $"An exception has been trigger \n Exception: {eventArgs.Exception.Message}" +
                        $"\n Source: {eventArgs.Exception.Source} \n StackTrace: {eventArgs.Exception.StackTrace}");
                };}
And it happens that everytime I implement AWS.Logger.NLog, it catches the next exception: 

An exception has been trigger 
Exception: Could not load the specified file.
Source: System.Private.CoreLib 
StackTrace: at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

**Comment by klaytaybai** [comment]
Hi @Jhordan92, can you please first follow my recommendations for following the config in the README or sample that I suggested on your other issue?  Then let me know if this is still an issue for you.  Thanks.

**Comment by Jhordan92** [comment]
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="c:\logs\provider\internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
 
    <target name="aws" type="AWSTarget" logGroup="Group" region="region"/>
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
   
    <logger name="*" minlevel="Debug" writeTo="aws" />
  </rules>
</nlog>
```
My current config

**Comment by snakefoot** [comment]
If you are using NetFramework (and not NetCore), then try and downgrade to AWS.Logger.NLog ver. 1.3.1 (Only use 1.3.2 for NetCore):

https://www.nuget.org/packages/AWS.Logger.NLog/1.3.1

For some unknown reason AWS-Team have not yet released valid 1.3.2 packages.

**Comment by Jhordan92** [comment]
The error was occurring when the API was in NetCore 2.1
We are currently in 2.2 and it continues to show that exception.

**Comment by snakefoot** [comment]
> Do you think that a downgrade could work in that case too?

Maybe worth a shot

**Comment by Jhordan92** [comment]
> > Do you think that a downgrade could work in that case too?
> 
> Maybe worth a shot

Done, and the exception persist

**Comment by Jhordan92** [comment]
I got an update on this issue
Hello, me again with more infor

When my nlog.config file doesn't have this lines:
 <extensions>
      <add assembly="NLog.AWS.Logger" />
  </extensions>
It can't find the type AWSTarget, but when I do have them, everything works, except that that's when the exception is catch by my FirstChanceException event, so I believe it's something about the NLog.AWS.Logger dll

**Comment by klaytaybai** [comment]
@Jhordan92, your response seems to be missing the lines you referenced

**Comment by Jhordan92** [comment]
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
>       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>       autoReload="true"
>       internalLogLevel="Info"
>       internalLogFile="c:\logs\provider\internal-nlog.txt">
> 
>   
>   <extensions>
>     <add assembly="NLog.AWS.Logger" />
>   </extensions>
> 
>   
>   <targets>
>     
>  
>     <target name="aws" type="AWSTarget" logGroup="Group" region="region"/>
>   </targets>
> 
>   
>   <rules>
>    
>     <logger name="*" minlevel="Debug" writeTo="aws" />
>   </rules>
> </nlog>
> ```
> 
> My current config

They are there

**Comment by Jhordan92** [comment]
> @Jhordan92, your response seems to be missing the lines you referenced

Thanks, I corrected the response

**Comment by ganpatsharma111** [comment]
Hi,

we want to integrate cloudwatch in web api project. app using dotnet core 2.2 framework.

Is it right approach to use AWS.Logger.NLog nuget package and NLog in web api application?

Is it supportable to dotnet core 2.2?

Please suggest.

Thanks

**Comment by ganpatsharma111** [comment]
Hi, 
I am working on dotnet core api project. I want to integrate the cloudwatch in application to write logs on cloudwatch. We are using dotnet core 2.2 and AWS.LOGGER.NLOG 1.4 latest version. 
We are hosting our application on EC2 IIS Server.

On executing api thrown below error:-

Error AWSTarget(Name=aws) - CloudWatch Network Error - ServiceUrl=https://logs.eu-west-2.amazonaws.com/ Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)

   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()

   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task)

   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy)

   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp)

   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()

   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

2019-08-19 10:38:09.9321 Error AWSTarget(Name=aws) - CloudWatch Network Error - ServiceUrl=https://logs.eu-west-2.amazonaws.com/ Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)

   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()

   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task)

   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy)

   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp)

   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()

   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()

   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)

   at AWS.Logger.Core.AWSLoggerCore.LogEventTransmissionSetup(CancellationToken token)

   at AWS.Logger.Core.AWSLoggerCore.Monitor(CancellationToken token)

Below is the sample for NLog file:-
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      autoReload="true" throwExceptions="true" throwConfigExceptions="true" internalLogLevel="Error" internalLogFile="c:\file.txt">
   <extensions> 
     <add assembly="NLog.AWS.Logger" />
   </extensions>
  <targets async="true">
    <target name="aws" 
            type="AWSTarget" 
            logGroup="prod" 
            LogStreamNamePrefix="Admin-Api" 
            LogStreamNameSuffix=".log" 
            region="***" 
            profile="default"
            layout=" ${level} | ${longdate} | ${callsite} | ${message}"/>
  </targets>
  <rules >
    <logger name="*" minLevel="Info" levels="Debug,Info,Trace,Error" writeTo="aws" enabled="true" />
  </rules>
</nlog>


Please suggest.

Thanks,

**Comment by ashishdhingra** [comment]
Hi @Jhordan92,

Good afternoon.

I was going through the issue backlog and came across this one. Please let me know if this is still the issue or if this could be closed.

If this is still an issue, it would be helpful if you could share your use case, reproduction steps, sample code and logs (if any) for troubleshooting.

Thanks,
Ashish
