### ISSUE TITLE
Error when deployed to Lightstream

### ISSUE THREAD

**Issue by genii90** [aws/aws-logging-dotnet#97]
I am using ASP.NET Core Logging in a .NET core application. It works fine on my development machine but throws the error below when my application starts up in a deployed AWS Lightstream environment. I do not understand why the underlying Lightstream Ubuntu 18.04 host (with VPC pairing) of my application is trying to use its own role. What would happen if I deployed my application to Azure or Google Cloud? Would there be some platform specific settings I would need consider?

```
Amazon.CloudWatchLogs.AmazonCloudWatchLogsException: User: arn:aws:sts::xxxxxxxxxxxx :assumed-role/AmazonLightsailInstanceRole/i-xxxxxxxxxxxx is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:us-east-1:xxxxxxxxxxxx :log-group::log-stream: ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AWS.Logger.Core.AWSLoggerCore.LogEventTransmissionSetup(CancellationToken token)
   at AWS.Logger.Core.AWSLoggerCore.Monitor(CancellationToken token)
```

**Comment by klaytaybai** [comment]
How are you using [credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) in your application?  I'm guessing that this role is from the instance's default credentials. You should consider configuring your credentials to whatever users or roles fit your needs best.

**Comment by genii90** [comment]
In appsettings.json:

```
"AWS": {
    "Region": "us-east-1",
    "UserPoolClientId": "someClientId",
    "UserPoolClientSecret": "SomePoolClientSecret",
    "UserPoolId": "somePoolId",
    "ProfilesLocation": "/path/to/myCredentialsFile",
    "Profile": "default"
  }
```

myCredentialsFile:

```
[default]
aws_access_key_id=myAccessKey
aws_secret_access_key=mySecretAccessKey
```

**Comment by genii90** [comment]
Seems like setting a custom location for "ProfilesLocation": "/path/to/myCredentialsFile" was being ignored. It worked once I put my credentials file at location: _~/.aws/credentials_
